# Generated by Django 2.2.7 on 2019-11-25 21:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 21, 52, 59, 511852, tzinfo=utc), verbose_name='Fecha de publicación'),
        ),
    ]
